// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJ5WYtFOOS1LVrLtjaXat4uI6zQBskFA',
    appId: '1:1033064514046:web:428019c9739af649b0c0af',
    messagingSenderId: '1033064514046',
    projectId: 'urbanera-79bfc',
    authDomain: 'urbanera-79bfc.firebaseapp.com',
    storageBucket: 'urbanera-79bfc.appspot.com',
    measurementId: 'G-QCVL49922X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRLPQmLuY8XJ1qZsq4lhPEQK4v55XcXlA',
    appId: '1:1033064514046:android:30abca37c3e8606cb0c0af',
    messagingSenderId: '1033064514046',
    projectId: 'urbanera-79bfc',
    storageBucket: 'urbanera-79bfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgdtxOvDaeqnMQfHFe9mfGs7CiFOZjrrU',
    appId: '1:1033064514046:ios:bd13d6b1f93ac552b0c0af',
    messagingSenderId: '1033064514046',
    projectId: 'urbanera-79bfc',
    storageBucket: 'urbanera-79bfc.appspot.com',
    iosBundleId: 'com.example.shoppersEcommerceFlutterUiKit',
  );
}
